### PR TITLE
Python 3.9 compatibility

### PR DESCRIPTION
**Pull request by hroncok**

### CODE REVIEW

**Comment by hroncok** [comment]
Oh, this is incomplete, I missed a file.

**Comment by hroncok** [comment]
Now it passes.

**Comment by jterrace** [comment]
Thanks!

**Comment by paulmelnikow** [comment]
@jterrace Hi! Would it be possible to cut a 0.7.2 release with this fix?

**Comment by paulmelnikow** [comment]
Hi @jterrace Wanted to follow up on this! Any chance you could cut a release which includes this fix? Thanks!

**Comment by paulmelnikow** [comment]
This was released in https://github.com/pycollada/pycollada/commit/ce00fd141240658efa79417622fb751129951c7a.

**Pull request merged**
