### PR TITLE
fix failing tests

### PR DESCRIPTION
**Pull request by speleo3**
- img.tostring() -> img.tobytes()
- numpy.ndarray constant comparison: use "is" instead of "=="
- test_geometry_triangleset_adding: move primitives.append(triangleset) after TriangleSet.load (guess by example of other tests)

Tested with 3.6.2 and 2.7.14

### CODE REVIEW

**Comment by jterrace** [comment]
Does this fix #61 ?

**Comment by speleo3** [comment]
Yes this fixes #61

**Comment by jterrace** [comment]
Awesome, thanks for fixing that. And how come you had to remove 2.6 and 3.2?

I'm okay doing that, since I think the main versions now are 2.7, 3.4, 3.5, and 3.6:
https://docs.python.org/devguide/index.html#branchstatus

Just curious why though. Could you also add 3.5?

**Comment by speleo3** [comment]
For Python 2.6, installation of **unittest2** fails on Travis:
https://travis-ci.org/pycollada/pycollada/jobs/212010766

For Python 3.2, installation of **lxml** fails on Travis (DEPS="lxml"):
https://travis-ci.org/pycollada/pycollada/jobs/297607561

Sure I can add 3.5.

**Comment by jterrace** [comment]
Thank you! One more thing, could I get you to add your name to the AUTHORS file?

**Comment by jterrace** [comment]
Thanks again!

**Pull request merged**
